// http://williamchyr.com/2013/11/unity-shaders-depth-and-normal-textures/
Shader "Custom/DepthNoCull" {
	SubShader{
	Tags { "RenderType" = "Opaque" }
	//Tags {"Queue" = "Transparent" "RenderType" = "Transparent" }
	LOD 100
	ZWRITE On
	//ZWRITE Off
	Cull Off

	Pass{
	CGPROGRAM
	#pragma vertex vert
	#pragma fragment frag
	#include "UnityCG.cginc"

	#include "HairCommon.cginc"


	sampler2D _CameraDepthTexture;
	sampler2D _DepthCulled;
	
	// generated by TestScreenPosRunner
	float4 _DepthCameraPlanes;

	struct v2f {
		float4 pos : SV_POSITION;
		float4 scrPos : TEXCOORD1;
		float3 viewPos : TEXCOORD2;
	};

	//Vertex Shader
	v2f vert(appdata_base v) {
		v2f o;
		o.pos = UnityObjectToClipPos(v.vertex);
		o.scrPos = ComputeScreenPos(o.pos);
		o.viewPos = UnityObjectToViewPos(v.vertex);

		return o;
	}

	//Fragment Shader
	float4 frag(v2f i) : COLOR{
		//float depthValue = Linear01Depth(tex2Dproj(_CameraDepthTexture, UNITY_PROJ_COORD(i.scrPos)).r);
		//float culledDepth = tex2Dproj(_DepthCulled, UNITY_PROJ_COORD(i.scrPos)).r;
		float culledDepth = tex2D(_DepthCulled, i.scrPos).r;

		//float culledDepth = tex2Dproj(_DepthCulled, UNITY_PROJ_COORD(i.scrPos)).r;
		//float depthValue = Linear01Depth(i.pos.z);
		float depthValue = Normalize_Depth(-i.viewPos.z, _DepthCameraPlanes.x, _DepthCameraPlanes.y, 1);

		//float d = culledDepth;
		float d = depthValue;
		if (culledDepth < depthValue) {
			d = culledDepth;
		}

		float4 depth;

		depth.r = d;
		depth.g = 0;
		depth.b = 0;

		depth.a = 0;
		//discard;
		return depth;

		}
		ENDCG
		}
	}
		FallBack "Diffuse"
}